// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type AiPlan struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	RawData   json.RawMessage
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Guide struct {
	ID         uuid.UUID
	Name       string
	Bio        string
	Location   string
	Expertise  string
	Rating     int32
	HourlyRate string
	Available  bool
}

type GuideBooking struct {
	ID        uuid.UUID
	GuideID   uuid.NullUUID
	GroupID   uuid.NullUUID
	Status    sql.NullString
	BookedAt  sql.NullTime
	UpdatedAt sql.NullTime
}

type GuideBookingRequest struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	UserID    uuid.UUID
	GuideID   uuid.UUID
	Status    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type PasswordToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Token     string
	CreatedAt sql.NullTime
	ExpiresAt time.Time
	UpdatedAt sql.NullTime
}

type TravelGroup struct {
	ID          uuid.UUID
	CreatorID   uuid.UUID
	Name        string
	Description string
	PlanID      uuid.UUID
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type TravelGroupsMember struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	UserID    uuid.UUID
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type TravelGroupsRequest struct {
	ID        uuid.UUID
	GroupID   uuid.UUID
	UserID    uuid.UUID
	Status    string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type TravelPlanDetail struct {
	ID        uuid.UUID
	CreatorID uuid.UUID
	Place     string
	StartDate string
	EndDate   string
	TripType  string
	Pets      bool
	Interests []string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	Name           string
	Age            int32
	PhoneNumber    string
	Email          string
	PasswordHash   string
	TokenVersion   sql.NullInt32
	AccessLevel    sql.NullString
	VerifiedStatus sql.NullBool
	CreatedAt      sql.NullTime
	UpdatedAt      sql.NullTime
	LastLoggedIn   sql.NullTime
}
